# Prices are stored in integer cents (e.g. 3499 => $34.99).
board_games = [
  { name: "Catan", price_cents: 3499, condition: "mint" },
  { name: "Ticket to Ride", price_cents: 1250, condition: "good" },
  { name: "Pandemic", price_cents: 2700, condition: "excellent" },
  { name: "Carcassonne", price_cents: 875, condition: "as_is" },
  { name: "Dominion", price_cents: 4500, condition: "mint" },
  { name: "Azul", price_cents: 1999, condition: "good" },
  { name: "7 Wonders", price_cents: 3850, condition: "excellent" },
  { name: "Splendor", price_cents: 2200, condition: "mint" },
  { name: "Wingspan", price_cents: 4999, condition: "good" },
  { name: "Codenames", price_cents: 1125, condition: "as_is" },
  { name: "Betrayal at House on the Hill", price_cents: 3300, condition: "excellent" },
  { name: "Gloomhaven", price_cents: 4750, condition: "mint" },
  { name: "Terraforming Mars", price_cents: 4100, condition: "good" },
  { name: "Dixit", price_cents: 1675, condition: "excellent" },
  { name: "Agricola", price_cents: 2999, condition: "as_is" },
  { name: "Power Grid", price_cents: 3600, condition: "mint" },
  { name: "Lords of Waterdeep", price_cents: 2350, condition: "good" },
  { name: "Arkham Horror", price_cents: 4400, condition: "excellent" },
  { name: "King of Tokyo", price_cents: 1825, condition: "as_is" },
  { name: "Smallworld", price_cents: 3100, condition: "mint" },
  { name: "Race for the Galaxy", price_cents: 1499, condition: "good" },
  { name: "Forbidden Island", price_cents: 950, condition: "as_is" },
  { name: "Pandemic Legacy Season 1", price_cents: 4800, condition: "excellent" },
  { name: "Through the Ages", price_cents: 4375, condition: "mint" },
  { name: "Istanbul", price_cents: 2600, condition: "good" },
  { name: "Battlestar Galactica", price_cents: 3999, condition: "as_is" },
  { name: "Dead of Winter", price_cents: 3550, condition: "excellent" },
  { name: "Viticulture", price_cents: 4600, condition: "mint" },
  { name: "Coup", price_cents: 725, condition: "good" },
  { name: "Sheriff of Nottingham", price_cents: 2100, condition: "as_is" },
  { name: "Tokaido", price_cents: 1750, condition: "excellent" },
  { name: "Robinson Crusoe", price_cents: 4000, condition: "mint" },
  { name: "Mysterium", price_cents: 2875, condition: "good" },
  { name: "Twilight Struggle", price_cents: 3700, condition: "as_is" },
  { name: "Concordia", price_cents: 3250, condition: "excellent" },
  { name: "Pandemic Iberia", price_cents: 2499, condition: "mint" },
  { name: "Spirit Island", price_cents: 5000, condition: "good" },
  { name: "Everdell", price_cents: 3025, condition: "excellent" },
  { name: "The Resistance", price_cents: 650, condition: "mint" },
  { name: "Bruges", price_cents: 2000, condition: "good" },
  { name: "Blood Rage", price_cents: 4575, condition: "as_is" },
  { name: "Village", price_cents: 1500, condition: "excellent" },
  { name: "Hive", price_cents: 1350, condition: "mint" },
  { name: "Quacks of Quedlinburg", price_cents: 2550, condition: "as_is" },
  { name: "Mansions of Madness", price_cents: 4700, condition: "mint" },
  { name: "Patchwork", price_cents: 1075, condition: "good" },
  { name: "Great Western Trail", price_cents: 4450, condition: "as_is" }
]

Game.transaction do
  Game.delete_all
  board_games.each { |attributes| Game.create!(attributes) }
end
